/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ApiAccountRouteImport } from './routes/api.account'
import { Route as ApiVaultRouteImport } from './routes/api.vault'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAccountRouteImport } from './routes/app.account'
import { Route as AppGenerateRouteImport } from './routes/app.generate'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppVaultRouteImport } from './routes/app.vault'
import { Route as ApiAuthChangePasswordRouteImport } from './routes/api.auth.change-password'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiAuthMeRouteImport } from './routes/api.auth.me'
import { Route as ApiAuthPreloginRouteImport } from './routes/api.auth.prelogin'
import { Route as ApiAuthRecoveryBeginRouteImport } from './routes/api.auth.recovery-begin'
import { Route as ApiAuthRecoveryCompleteRouteImport } from './routes/api.auth.recovery-complete'
import { Route as ApiAuthRegisterRouteImport } from './routes/api.auth.register'
import { Route as ApiAuthVaultKeyMaterialRouteImport } from './routes/api.auth.vault-key-material'
import { Route as ApiVaultIdRouteImport } from './routes/api.vault.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountRoute = ApiAccountRouteImport.update({
  id: '/api/account',
  path: '/api/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultRoute = ApiVaultRouteImport.update({
  id: '/api/vault',
  path: '/api/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppGenerateRoute = AppGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultRoute = AppVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthChangePasswordRoute = ApiAuthChangePasswordRouteImport.update({
  id: '/api/auth/change-password',
  path: '/api/auth/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPreloginRoute = ApiAuthPreloginRouteImport.update({
  id: '/api/auth/prelogin',
  path: '/api/auth/prelogin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRecoveryBeginRoute = ApiAuthRecoveryBeginRouteImport.update({
  id: '/api/auth/recovery-begin',
  path: '/api/auth/recovery-begin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRecoveryCompleteRoute = ApiAuthRecoveryCompleteRouteImport.update({
  id: '/api/auth/recovery-complete',
  path: '/api/auth/recovery-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVaultKeyMaterialRoute = ApiAuthVaultKeyMaterialRouteImport.update({
  id: '/api/auth/vault-key-material',
  path: '/api/auth/vault-key-material',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultIdRoute = ApiVaultIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiVaultRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/account': typeof ApiAccountRoute
  '/api/vault': typeof ApiVaultRouteWithChildren
  '/app/account': typeof AppAccountRoute
  '/app/generate': typeof AppGenerateRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/vault': typeof AppVaultRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/prelogin': typeof ApiAuthPreloginRoute
  '/api/auth/recovery-begin': typeof ApiAuthRecoveryBeginRoute
  '/api/auth/recovery-complete': typeof ApiAuthRecoveryCompleteRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/vault-key-material': typeof ApiAuthVaultKeyMaterialRoute
  '/api/vault/$id': typeof ApiVaultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/account': typeof ApiAccountRoute
  '/api/vault': typeof ApiVaultRouteWithChildren
  '/app/account': typeof AppAccountRoute
  '/app/generate': typeof AppGenerateRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/vault': typeof AppVaultRoute
  '/app': typeof AppIndexRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/prelogin': typeof ApiAuthPreloginRoute
  '/api/auth/recovery-begin': typeof ApiAuthRecoveryBeginRoute
  '/api/auth/recovery-complete': typeof ApiAuthRecoveryCompleteRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/vault-key-material': typeof ApiAuthVaultKeyMaterialRoute
  '/api/vault/$id': typeof ApiVaultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/account': typeof ApiAccountRoute
  '/api/vault': typeof ApiVaultRouteWithChildren
  '/app/account': typeof AppAccountRoute
  '/app/generate': typeof AppGenerateRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/vault': typeof AppVaultRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/prelogin': typeof ApiAuthPreloginRoute
  '/api/auth/recovery-begin': typeof ApiAuthRecoveryBeginRoute
  '/api/auth/recovery-complete': typeof ApiAuthRecoveryCompleteRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/vault-key-material': typeof ApiAuthVaultKeyMaterialRoute
  '/api/vault/$id': typeof ApiVaultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/api/account'
    | '/api/vault'
    | '/app/account'
    | '/app/generate'
    | '/app/settings'
    | '/app/vault'
    | '/app/'
    | '/api/auth/change-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/prelogin'
    | '/api/auth/recovery-begin'
    | '/api/auth/recovery-complete'
    | '/api/auth/register'
    | '/api/auth/vault-key-material'
    | '/api/vault/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/api/account'
    | '/api/vault'
    | '/app/account'
    | '/app/generate'
    | '/app/settings'
    | '/app/vault'
    | '/app'
    | '/api/auth/change-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/prelogin'
    | '/api/auth/recovery-begin'
    | '/api/auth/recovery-complete'
    | '/api/auth/register'
    | '/api/auth/vault-key-material'
    | '/api/vault/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/api/account'
    | '/api/vault'
    | '/app/account'
    | '/app/generate'
    | '/app/settings'
    | '/app/vault'
    | '/app/'
    | '/api/auth/change-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/prelogin'
    | '/api/auth/recovery-begin'
    | '/api/auth/recovery-complete'
    | '/api/auth/register'
    | '/api/auth/vault-key-material'
    | '/api/vault/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAccountRoute: typeof ApiAccountRoute
  ApiVaultRoute: typeof ApiVaultRouteWithChildren
  ApiAuthChangePasswordRoute: typeof ApiAuthChangePasswordRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthPreloginRoute: typeof ApiAuthPreloginRoute
  ApiAuthRecoveryBeginRoute: typeof ApiAuthRecoveryBeginRoute
  ApiAuthRecoveryCompleteRoute: typeof ApiAuthRecoveryCompleteRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiAuthVaultKeyMaterialRoute: typeof ApiAuthVaultKeyMaterialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account': {
      id: '/api/account'
      path: '/api/account'
      fullPath: '/api/account'
      preLoaderRoute: typeof ApiAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vault': {
      id: '/api/vault'
      path: '/api/vault'
      fullPath: '/api/vault'
      preLoaderRoute: typeof ApiVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/generate': {
      id: '/app/generate'
      path: '/generate'
      fullPath: '/app/generate'
      preLoaderRoute: typeof AppGenerateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vault': {
      id: '/app/vault'
      path: '/vault'
      fullPath: '/app/vault'
      preLoaderRoute: typeof AppVaultRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/change-password': {
      id: '/api/auth/change-password'
      path: '/api/auth/change-password'
      fullPath: '/api/auth/change-password'
      preLoaderRoute: typeof ApiAuthChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/prelogin': {
      id: '/api/auth/prelogin'
      path: '/api/auth/prelogin'
      fullPath: '/api/auth/prelogin'
      preLoaderRoute: typeof ApiAuthPreloginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/recovery-begin': {
      id: '/api/auth/recovery-begin'
      path: '/api/auth/recovery-begin'
      fullPath: '/api/auth/recovery-begin'
      preLoaderRoute: typeof ApiAuthRecoveryBeginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/recovery-complete': {
      id: '/api/auth/recovery-complete'
      path: '/api/auth/recovery-complete'
      fullPath: '/api/auth/recovery-complete'
      preLoaderRoute: typeof ApiAuthRecoveryCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/vault-key-material': {
      id: '/api/auth/vault-key-material'
      path: '/api/auth/vault-key-material'
      fullPath: '/api/auth/vault-key-material'
      preLoaderRoute: typeof ApiAuthVaultKeyMaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vault/$id': {
      id: '/api/vault/$id'
      path: '/$id'
      fullPath: '/api/vault/$id'
      preLoaderRoute: typeof ApiVaultIdRouteImport
      parentRoute: typeof ApiVaultRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppGenerateRoute: typeof AppGenerateRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVaultRoute: typeof AppVaultRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppGenerateRoute: AppGenerateRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVaultRoute: AppVaultRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiVaultRouteChildren {
  ApiVaultIdRoute: typeof ApiVaultIdRoute
}

const ApiVaultRouteChildren: ApiVaultRouteChildren = {
  ApiVaultIdRoute: ApiVaultIdRoute,
}

const ApiVaultRouteWithChildren = ApiVaultRoute._addFileChildren(
  ApiVaultRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAccountRoute: ApiAccountRoute,
  ApiVaultRoute: ApiVaultRouteWithChildren,
  ApiAuthChangePasswordRoute: ApiAuthChangePasswordRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthPreloginRoute: ApiAuthPreloginRoute,
  ApiAuthRecoveryBeginRoute: ApiAuthRecoveryBeginRoute,
  ApiAuthRecoveryCompleteRoute: ApiAuthRecoveryCompleteRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiAuthVaultKeyMaterialRoute: ApiAuthVaultKeyMaterialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
